### PR TITLE
add characterLimit option

### LINKED ISSUE #3: Option to limit number of characters in the body of the issue [characterLimit]
It would be interesting if you had the option of not bringing all the text of the article, but just a few characters and a 'Read more: www.xpto.com'
RSS is bringing all the content from all the sites, and that ends up taking away the article's view.

### My sugestion:

Create `characterLimit` options.
- Default value: 0
     - If the person does not enter a value other than 0, they will continue to create an issue with all the content of the article, which is the current behavior.
- If the person reports a value above 0, actions will create the issue with the number of characters defined, 3 points at the end (...) and the footer `Read more: XXX`.

### Workflow Example:
``` yml
on:
  schedule:
    - cron: "0 11 * * *"

jobs:

  AssertQA:
    runs-on: ubuntu-latest
    steps:
      - uses: guilhem/rss-issues-action@0.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          feed: "https://medium.com/feed/assertqualityassurance"
          lastTime: "25h"
          labels: "AssertQA,RSS"
          characterLimit: 250
```

### Issue example:

>Hello guys,
 Continuing on reviewing some performance test tools, today is the turn of Jmeter and Gatling, which looks like more and more people are using nowadays. Remember always check your other options and see what better fits for your project...
>
>Read more: https://azevedorafaela.com/2020/06/22/load-tests-jmeter-vs-gatlin/

### PR DESCRIPTION
**Pull request by guilhem**
Fix #3

### CODE REVIEW

**Comment by guilhem** [comment]
@PauloGoncalvesBH can you try this PR with `uses: guilhem/rss-issues-action@27966e7`

**Comment by PauloGoncalvesBH** [comment]
My third and final suggestion is to complement the README with this new option 😅 

```diff
jobs:
  gke-release:
    runs-on: ubuntu-latest
    steps:
-     - uses: guilhem/rss-issues-action@0.0.1
+     - uses: guilhem/rss-issues-action@3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          feed: "https://cloud.google.com/feeds/kubernetes-engine-release-notes.xml"
+         characterLimit: "255"
          prefix: "[GKE]"
          dry-run: "false"
          lastTime: "92h"
          labels: "liens/Kubernetes"
```

**Comment by guilhem** [comment]
You can test it with branch `3` ;)

**Comment by PauloGoncalvesBH** [comment]
I really liked the change, it's great 🎉

**Pull request merged**
